version: '3.8'

services:
  db:
    image: ${DB_IMAGE}
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    depends_on:
      - db
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: thanh.le@stunited.vn
      PGADMIN_DEFAULT_PASSWORD: password
    restart: unless-stopped
    networks:
      - my_network

volumes:
  postgres-data:

networks:
  my_network:
    name: my_network
